<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TokoSeeder extends Seeder
{
    public function run(): void
    {
        $toko = [
            [
                'toko_id' => 'TKO001',
                'nama_toko' => 'Toko Kue Sugeng',
                'pemilik' => 'Pak Sugeng',
                'alamat' => 'Pasar Klojen Jl. Cokroaminoto No. 2, 65111, Jl. Cokroaminoto No.2 D, 3, Klojen, Kec. Klojen, Kota Malang, Jawa Timur 65111',
                'wilayah_kecamatan' => 'Klojen',
                'wilayah_kelurahan' => 'Klojen',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '08577633404',
                'latitude' => '-7.96233746',
                'longitude' => '112.62745857',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO002',
                'nama_toko' => 'Risol Pastel Pasar Oro Oro Dowo',
                'pemilik' => 'Bu Katharine',
                'alamat' => 'Jl. Guntur No.20, Oro-oro Dowo, Kec. Klojen, Kota Malang, Jawa Timur 65112',
                'wilayah_kecamatan' => 'Klojen',
                'wilayah_kelurahan' => 'Oro-oro Dowo',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '083801119854',
                'latitude' => '-7.96873921',
                'longitude' => '112.62825346',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO003',
                'nama_toko' => 'Warung Sayur Segar Kalpataru',
                'pemilik' => 'WSS',
                'alamat' => 'Jl. Kalpataru, Jatimulyo, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141',
                'wilayah_kecamatan' => 'Lowokwaru',
                'wilayah_kelurahan' => 'Jatimulyo',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '081333484193',
                'latitude' => '-7.94929663',
                'longitude' => '112.62812958',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO004',
                'nama_toko' => 'Warung Sayur Segar Danau Sentani',
                'pemilik' => 'WSS',
                'alamat' => 'Jl. Danau Sentani Raya, Madyopuro, Kec. Kedungkandang, Kota Malang, Jawa Timur 65139',
                'wilayah_kecamatan' => 'Kedungkandang',
                'wilayah_kelurahan' => 'Madyopuro',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '081235640005',
                'latitude' => '-7.97808666',
                'longitude' => '112.66380471',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO005',
                'nama_toko' => 'Warung Sayur Segar Bandulan',
                'pemilik' => 'WSS',
                'alamat' => 'Jl. Bandulan No.26, Bandulan, Kec. Sukun, Kota Malang, Jawa Timur 65146',
                'wilayah_kecamatan' => 'Sukun',
                'wilayah_kelurahan' => 'Bandulan',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '081235640005',
                'latitude' => '-7.98305926',
                'longitude' => '112.60693679',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO006',
                'nama_toko' => 'Warung Sayur Segar Sulfat',
                'pemilik' => 'WSS',
                'alamat' => 'Jl. Sulfat No.99C, Pandanwangi, Kec. Blimbing, Kota Malang, Jawa Timur 65122',
                'wilayah_kecamatan' => 'Blimbing',
                'wilayah_kelurahan' => 'Pandanwangi',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '085707633404',
                'latitude' => '-7.96176369',
                'longitude' => '112.65192388',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO007',
                'nama_toko' => 'Warung Sayur Segar Candi Panggung (RRI)',
                'pemilik' => 'WSS',
                'alamat' => 'Jl. Candi Panggung No.61, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur 65142',
                'wilayah_kecamatan' => 'Lowokwaru',
                'wilayah_kelurahan' => 'Mojolangu',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '083801119854',
                'latitude' => '-7.93848120',
                'longitude' => '112.62285070',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO008',
                'nama_toko' => 'Toko Firdaus',
                'pemilik' => 'Umi',
                'alamat' => 'Jl. Tlk. Bayur, Pandanwangi, Kec. Blimbing, Kota Malang, Jawa Timur 65125',
                'wilayah_kecamatan' => 'Blimbing',
                'wilayah_kelurahan' => 'Pandanwangi',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '085100625116',
                'latitude' => '-7.93205926',
                'longitude' => '112.66199201',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO009',
                'nama_toko' => 'Toko Kue Selat Bali',
                'pemilik' => 'Bu Selat Bali',
                'alamat' => 'Jalan Selat Bali Blok E0 No.1A, Sawojajar, Kedungkandang, Lesanpuro, Kec. Kedungkandang, Kota Malang, Jawa Timur 65139',
                'wilayah_kecamatan' => 'Kedungkandang',
                'wilayah_kelurahan' => 'Sawojajar',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '081334945436',
                'latitude' => '-7.98120774',
                'longitude' => '112.65703797',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO010',
                'nama_toko' => 'Toko Kue Jaya Cookies',
                'pemilik' => 'Pak Adi',
                'alamat' => 'Griya Shanta, Blk. H No.402, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur 65142',
                'wilayah_kecamatan' => 'Lowokwaru',
                'wilayah_kelurahan' => 'Mojolangu',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '081333484193',
                'latitude' => '-7.93560839',
                'longitude' => '112.62383215',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO011',
                'nama_toko' => 'Istana Sayur',
                'pemilik' => 'WIS',
                'alamat' => 'Jl. Raya Tlogomas No.93, Tlogomas, Kec. Lowokwaru, Kota Malang, Jawa Timur 65144',
                'wilayah_kecamatan' => 'Lowokwaru',
                'wilayah_kelurahan' => 'Tlogomas',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '081232237329',
                'latitude' => '-7.93268449',
                'longitude' => '112.60281447',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO012',
                'nama_toko' => 'Pusat Mie Gloria',
                'pemilik' => 'Gloria',
                'alamat' => 'Jl. Zainul Arifin No.18 A, Sukoharjo, Kec. Klojen, Kota Malang, Jawa Timur 65119',
                'wilayah_kecamatan' => 'Klojen',
                'wilayah_kelurahan' => 'Sukoharjo',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '0341350302',
                'latitude' => '-7.98231273',
                'longitude' => '112.63441045',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO013',
                'nama_toko' => 'Koperasi Jasa Pegawai Republik Indonesia Universitas Brawijaya',
                'pemilik' => 'Universitas Brawijaya',
                'alamat' => 'Jl. MT. Haryono No.169, Ketawanggede, Kec. Lowokwaru, Kota Malang, Jawa Timur 65145',
                'wilayah_kecamatan' => 'Lowokwaru',
                'wilayah_kelurahan' => 'Ketawanggede',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '0341552995',
                'latitude' => '-7.95205194',
                'longitude' => '112.61312419',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO014',
                'nama_toko' => 'Warung Sayur',
                'pemilik' => 'Pak Andre',
                'alamat' => 'Jalan Ikan Tombro Barat, Tunjungsekar, Malang, Jawa Timur',
                'wilayah_kecamatan' => 'Lowokwaru',
                'wilayah_kelurahan' => 'Tunjungsekar',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '08888888888',
                'latitude' => '-7.92398060',
                'longitude' => '112.63525533',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO015',
                'nama_toko' => 'Toko Twins',
                'pemilik' => 'Bu Sulis',
                'alamat' => 'Jl. Emas No.70, Purwantoro, Kec. Blimbing, Kota Malang, Jawa Timur 65122',
                'wilayah_kecamatan' => 'Blimbing',
                'wilayah_kelurahan' => 'Purwantoro',
                'wilayah_kota_kabupaten' => 'Kota Malang',
                'nomer_telpon' => '081945590055',
                'latitude' => '-7.95434973',
                'longitude' => '112.65014201',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO016',
                'nama_toko' => 'Koperasi Dinkes',
                'pemilik' => 'Dinas Kesehatan Kabupaten Malang',
                'alamat' => 'Jl. Panji No.120, Penarukan, Kec. Kepanjen, Kabupaten Malang, Jawa Timur 65163',
                'wilayah_kecamatan' => 'Kepanjen',
                'wilayah_kelurahan' => 'Kepanjen',
                'wilayah_kota_kabupaten' => 'Kabupaten Malang',
                'nomer_telpon' => '0341393730',
                'latitude' => '-8.13942811',
                'longitude' => '112.57129916',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO017',
                'nama_toko' => 'Warung Omah Sayur',
                'pemilik' => 'Omah Sayur',
                'alamat' => 'Jl. Sidomakmur No.73, Sengkaling, Mulyoagung, Kec. Dau, Kabupaten Malang, Jawa Timur 65151',
                'wilayah_kecamatan' => 'Dau',
                'wilayah_kelurahan' => 'Mulyoagung',
                'wilayah_kota_kabupaten' => 'Kabupaten Malang',
                'nomer_telpon' => '081383106147',
                'latitude' => '-7.89500000',
                'longitude' => '112.58500000',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO018',
                'nama_toko' => 'Aneka Kue Basah Sengkaling',
                'pemilik' => 'Arya',
                'alamat' => 'Jl. Sidomakmur No.113a, Jetak Ngasri, Mulyoagung, Kec. Dau, Kabupaten Malang, Jawa Timur 65151',
                'wilayah_kecamatan' => 'Dau',
                'wilayah_kelurahan' => 'Mulyoagung',
                'wilayah_kota_kabupaten' => 'Kabupaten Malang',
                'nomer_telpon' => '085230598754',
                'latitude' => '-7.92323317',
                'longitude' => '112.57628101',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO019',
                'nama_toko' => 'Toko Hijrah',
                'pemilik' => 'Hijrah',
                'alamat' => 'Jl. Jambu No.11, Semanding, Sumbersekar, Kec. Dau, Kabupaten Malang, Jawa Timur 65151',
                'wilayah_kecamatan' => 'Dau',
                'wilayah_kelurahan' => 'Sumbersekar',
                'wilayah_kota_kabupaten' => 'Kabupaten Malang',
                'nomer_telpon' => '088889088',
                'latitude' => '-7.92818599',
                'longitude' => '112.56587513',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO020',
                'nama_toko' => 'Toko Kue Wendit',
                'pemilik' => 'Bu Ifa',
                'alamat' => 'Jl. Raya Wendit Tim. No.8-16, Lowoksoro, Mangliawan, Kec. Pakis, Kabupaten Malang, Jawa Timur 65154',
                'wilayah_kecamatan' => 'Pakis',
                'wilayah_kelurahan' => 'Mangliawan',
                'wilayah_kota_kabupaten' => 'Kabupaten Malang',
                'nomer_telpon' => '0888898887',
                'latitude' => '-8.09983000',
                'longitude' => '112.64987000',
                'is_active' => 1,
            ],
            [
                'toko_id' => 'TKO021',
                'nama_toko' => 'Toko Kue Puspa',
                'pemilik' => 'Bu Puspa',
                'alamat' => 'Blk. GL 2 Perum Bumi Mondoroko Raya No.18 - 20, RT.001/RW.015, Krajan, Watugede, Kec. Singosari, Kabupaten Malang, Jawa Timur 65153',
                'wilayah_kecamatan' => 'Singosari',
                'wilayah_kelurahan' => 'Watugede',
                'wilayah_kota_kabupaten' => 'Kabupaten Malang',
                'nomer_telpon' => '08176458200',
                'latitude' => '-7.90960699',
                'longitude' => '112.66471998',
                'is_active' => 1,
            ],
        ];

        foreach ($toko as &$item) {
            $item['catatan_lokasi'] = null;
            $item['alamat_lengkap_geocoding'] = null;
            $item['geocoding_provider'] = 'interactive_map';
            $item['geocoding_accuracy'] = 'very high';
            $item['geocoding_confidence'] = '1.000';
            $item['geocoding_quality'] = 'excellent';
            $item['geocoding_score'] = '100.00';
            $item['geocoding_last_updated'] = now();
            $item['created_at'] = now();
            $item['updated_at'] = now();
            $item['user_create'] = null;
            $item['user_update'] = null;
        }

        DB::table('toko')->insert($toko);
    }
}
